localhub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prefik.urls')),
]

prefik/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import re_path
from prefik import views
from prefik.views import *
from django.urls import path

app_name = 'prefik'
handler404 = 'prefik.views.handler404'
urlpatterns=[
		path('',views.index, name='index'),
		path('blogs',views.blogs, name='blogs'),
		path('blogs/<slug>/', views.show, name='show'),
	]
if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prefik/models.py
from django.db import models

class Choice(models.Model):
	options = (
		('web','web'),
		('linux','linux'),
		('cloud','cloud'),
		('others','others')
		)
	name = models.CharField(max_length=10,choices=options,default='others')
	def __str__(self):
		return self.name

class Author(models.Model):
	author_name = models.CharField(max_length=15,blank=True)
	def __str__(self):
		return self.author_name


class Blog(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField(max_length=5000)
	publish_date = models.DateTimeField(auto_now_add=True)
	category = models.ManyToManyField(Choice,default='others') 
	author = models.ForeignKey(Author,on_delete=models.CASCADE)
	image = models.ImageField(blank=True)
	class Meta:
		ordering = ['-publish_date']
		
	def __str__(self):
		return f'{self.title} - {self.author}'

	def save(self, *args, **kwargs):
		self.title = self.title.lower()
		return super(Blog, self).save(*args, **kwargs)

prefik/forms.py
from django import forms
from django.forms import ModelForm
from prefik.models import Blog

class Blogform(ModelForm):
	class Meta:
		model = Blog
		fields = '__all__'
		widgets = {
			'title' : forms.TextInput(attrs={'id':'title','placeholder':'Please enter your title','autocomplete':'off'}),
			'content' : forms.Textarea(attrs={'rows':10,'cols':40,'id':'content','placeholder':'Add your content here ...','autocomplete':'off'}),
			'category' : forms.SelectMultiple(attrs={'id':'category'}),
			'author' : forms.TextInput(attrs={'id':'author','placeholder':'Please enter your author','autocomplete':'off',}),
			'image' : forms.FileInput(attrs={'id':'image'}),

		}

prefik/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404 , HttpResponse
from django.views.generic import TemplateView, ListView
from django.views import View
from django.conf import settings
from prefik.models import Blog
from prefik.forms import Blogform
from django.views.decorators.gzip import gzip_page

@gzip_page
def index(request):
	blogs = Blog.objects.all()[:3]
	return render(request, 'index.html',{'blogs':blogs})

def blogs(request):
	blogs  = Blog.objects.all()
	return render(request, 'blogs.html' ,{'blogs':blogs})

def show(request, slug):
	unslug = slug.replace('-', ' ') 
	detail = Blog.objects.get(title=unslug)
	return render(request, 'show.html',{'detail':detail})

def handler404(request,exception):
	data = {}
	return render(request, '404.html',data)



# Create your views here.

prefik/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>{% block title %}PREFik{% endblock %}</title>
	<link href="{% static 'images/prefik.png'%}" rel="shortcut icon">
    <meta name="theme-color" content="#" />
    <meta name="Description" content="# ">
    <meta name="Keywords" content="#">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&family=Montserrat:wght@800&family=Josefin+Sans&family=Roboto:wght@900&display=swap" rel="stylesheet"> 
<style>
    .navbar{height:4.5em;background-color:#FFFFFF!important;border:none!important;}
        .navbar-brand{font-family:'Montserrat',sans-serif;font-size:2em;color:#22282A!important;letter-spacing:1.5px;padding-top:0.95em;}
        .navbar-collapse{padding:0.5em 4em 0.2em 2em!important;background-color:#FFFFFF;}
        #link{font-family: 'Ubuntu', sans-serif;font-size:0.85em;color:#0C2A5F;letter-spacing:1px;}
        #link:hover{color:#113C88;text-decoration:underline;}
    @media screen and (max-width:600px){
    .navbar-collapse{padding:0em 4em 0em 2em!important;}
    .navbar-toggle .icon-bar{width:25px!important;height:3px!important;}
    .navbar-default .navbar-toggle .icon-bar{background-color:#26292C!important;}
    .navbar-default .navbar-toggle{border-color:#FFFFFF!important;}
    .navbar-default .navbar-toggle:focus, .navbar-default .navbar-toggle:hover {background-color:#FFFFFF;}

}
{% block css%}
{% endblock %}
</style>
</head>
<body>
{% block nav %}
<!--Navbar-Header-Section-Starts-->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><b>PreFik</b></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/" id="link">HOME</a></li>
                    <li><a href="/blogs" id="link">BLOGS</a></li>
                </ul>
            </div>
        </div>
    </nav>
<!--Navbar-Header-Section-Ends-->
{% endblock %}
<!--Content-->
{% block content %}{% endblock %}
<!--Content-ends-->
</body>
</html>

prefik/templates/blogs.html
{% extends 'base.html' %}
{%load static%}
{% block css %}
.blogs{width:70%;margin-top:6.4em;padding:0.4em 2.5em 1em 1.5em;}
		#blog{height:auto;background-color:#F7F7F7;padding:1.5em 1.5em 1.5em 2em; margin-top:2.2em;border:solid 1px #BABABA;border-style: dotted;}
		#blog-title{font-family:'Montserrat',sans-serif;font-size:1.6em;color:#302C2B;text-align:left;}
		#blog-date{font-family: 'Ubuntu',sans-serif;font-size:1em;color:#0A3F67;text-align:left;padding:1.5em 0 0.2em 1em;}
.extra{height:auto;font-family: 'Josefin Sans',sans-serif;font-size:1em;letter-spacing:1px;padding:1.5em 0 1em 0;}

@media screen and (max-width:600px){
	.blogs{width:100%;margin-top:5em;padding:0.4em 1em 1em 1.5em;}
	#blog{padding:1em 0.6em 1.5em 1em;margin-top:1.2em;}
	#blog-title{font-size:1.2em;}
	#blog-date{font-size:0.9em;}
}
{% endblock %}
{% block content%}
<div class="container-fluid text-center blogs">
	{% for b in blogs %}
		<a href="{% url 'prefik:show' b.title|slugify %}" style="text-decoration:none;">
			<div id="blog">
				<div id="blog-title">{{ b.title|title }}</div>
					<div id="blog-date">Posted On: {{ b.publish_date }}</div>
				</div>
		</a>
	{% endfor %}
	<div class="extra">
		<p>	&copy; 2020, All Rights Reserved | Prefik</p>
	</div>
</div>
{% endblock %}

prefik/templates/index.html
{% extends 'base.html' %}
{%load static%}
{% block css %}
.row{padding:0!important;}
.about{height:auto;background:none;padding:0!important;font-family:'Ubuntu',sans-serif;}
	#profile{padding:9em 0 2em 0;}
		#about-img{height:10em;width:10em;border-radius:50%;;}
		#about-name{color:#485566;font-size:1.5em;letter-spacing:0.1px;padding:0.8em 0 0em 0;}
	#aboutme{height:auto;background:#EEEEEE;padding:0em 1.5em 1em 1em;}
		#hr-line{width:8em;height:0.35em;background-color:#F18D09;margin-left:-2em;}
		#about-content{font-size:1.1em;text-align:left;color:#31363A;line-height:1.5em;margin-top:1.5em;letter-spacing:0.2px;}
		#sociallinks{text-align:left;margin-top:0.1em;border-top:solid 2px #DEDEDE;padding:0.8em 0 0.1em 0;}
		#social-icon{height:2em;width:2em;}
		#social-icon:hover{opacity:0.6;}
.newmain{height:auto;padding:4em 0 1em 2em;}
	#recent-head{text-align:left;font-family:'Josefin Sans',sans-serif;}
	.blogs{margin-top:0.2em;padding:0.4em 2.5em 1em 1.5em;}
		#blog{height:auto;background-color:#F7F7F7;padding:1.5em 1.5em 1.5em 2em; margin-top:2.2em;border:solid 1px #BABABA;border-style: dotted;}
		#blog:hover{filter:contrast(120%);}
		#blog-title{font-family:'Montserrat',sans-serif;font-size:1.6em;color:#302C2B;text-align:left;}
		#blog-date{font-family: 'Ubuntu',sans-serif;font-size:1em;color:#0A3F67;text-align:left;padding:1.5em 0 0.2em 1em;}

.extra{height:auto;font-family:'Josefin Sans',sans-serif;font-size:1em;letter-spacing:1px;padding:1.5em 0 1em 0;}

@media screen and (max-width:600px){
	#profile{padding:12em 0 2.5em 0;}
	#hr-line{width:12em;}
	#aboutme{padding:0em 1.5em 1em 1em;}
	.newmain{padding:1em 0.5em 1em 0.5em;}
		.blogs{padding:0.4em 0.5em 1em 0.5em;}
		#blog{padding:1em 1em 1.5em 1em;margin-top:1.2em;}
		#blog-title{font-size:1.2em;}
		#blog-date{font-size:0.9em;}
}	
{% endblock %}
{% block content%}
<div class="container-fluid text-center">
	<div class="row">
		<div class="col-sm-3 text-center about">
			<div id="profile">
				<img src="{% static 'images/profile.png' %}" id="about-img" />
				<h4 id="about-name">Hi I'm <b style="color:#222830;letter-spacing:1px;font-size:1em;">Hritik</b></h4>
			</div>
			<div id="aboutme">
				<hr id="hr-line">
				<p id="about-content">
					I'm a Linux Administrator at Wipro Limited and I write about Linux, Python, Django, Cloud and sometimes something non-technical.
				</p>
				<h5 style="font-family:'Ubuntu',sans-serif;font-weight:600;text-align:left;color:#41302A;letter-spacing:2px;padding-top:0.55em;">Lives in Delhi,India</h5>
				<br>
				<h5 style="font-family:'Ubuntu',sans-serif;color:#123854;text-align:left;letter-spacing:0px;">Feel free to Contact me</h5>
				<div id="sociallinks">
						<a href="https://www.facebook.com/profile.php?id=100009385909937" target="_blank"><img src="{% static 'images/social/facebook.png'%}" id="social-icon" /></a>&emsp; 
						<a href="mailto:shahihritik@gmail.com" target="_blank"><img src="{% static 'images/social/gmail.png'%}" id="social-icon" /></a>&emsp;
			            <a href="https://www.instagram.com/_iamhritik/" target="_blank"><img src="{% static 'images/social/instagram.png'%}" id="social-icon" /></a>&emsp;
			            <a href="https://github.com/iamhritik" target="_blank"><img src="{% static 'images/social/github.png'%}" id="social-icon"></a>&emsp;
			            <a href="https://twitter.com/_iamhritik" target="_blank"><img src="{% static 'images/social/twitter.png'%}" id="social-icon"></a>&emsp;
			            <a href="https://www.linkedin.com/in/hritik-01bb34165/" target="_blank"><img src="{% static 'images/social/linkedin.png'%}" id="social-icon"></a>&emsp;
				</div>
			</div>
		</div>
		<div class="col-sm-9 newmain">
			<h2 id="recent-head">Recent Posts</h2>
				<div class="blogs">
					{% for b in blogs %}
					<a href="{% url 'prefik:show' b.title|slugify %}" style="text-decoration:none;">
						<div id="blog">
							<div id="blog-title">{{ b.title|title }}</div>
							<div id="blog-date">Posted On: {{ b.publish_date|date:"F j, Y" }}</div>
						</div>
					</a>
					{% endfor %}
				</div>
		</div>
	</div>
	<div class="extra">
		<p>	&copy; 2020, All Rights Reserved | Prefik</p>
	</div>
</div>
{% endblock %}

prefik/templates/show.html
{% extends 'base.html' %}
{%load static%}
{% block css %}
.blog-detail{margin-top:9em;width:80%;}
	#blog-block{border:solid 4px #F0F0F0;padding:0.5em 2em 2em 2em;}
	#title{font-family:'Montserrat',sans-serif;font-size:2em;font-weight:600;color:#283743;padding:2em 1em 1em 1em;text-align:left;letter-spacing:0.2px;filter:contrast(120%);}
	#date{font-family:'Montserrat',sans-serif;font-size:1em;color:#FF470A;text-align:left;padding:0 0 0em 3em;}
	#content{font-family:'Ubuntu',sans-serif;font-size:1.1em;color:#0C1322;text-align:justify;margin-top:2em;padding:2em 2.5em 5em 2em;}
@media screen and (max-width:600px){
	.blog-detail{width:100%;margin-top:6em;}
	#blog-block{padding:0.4em 0.2em 1em 0.2em;}
	#title{font-size:1.8em;padding:1em 0.5em 1em 0.4em;}
	#date{font-size:0.9em;padding:0 0 0em 1.5em;}
	#content{font-size:1em;margin-top:2em;padding:2em 0.5em 4em 0.4em;}
}
{% endblock %}
{% block content%}
<div class="container-fluid text-center blog-detail">
	<div id="blog-block">
		<div id="title">{{ detail.title|title }}</div>
		<div id="date">Published On: {{ detail.publish_date|date:"F j, Y" }}</div>
		<div id="content">{{ detail.content|safe|linebreaksbr }}</div>
	</div>
</div>
{% endblock %}